channels:
  - conda-forge
  - bioconda

dependencies:
  - star>=2.7.11b,<3
  - r-seurat
  - r-irkernel
  - r-hdf5r 
  - r-wgcna 
  - r-igraph 
  - r-tidyverse 
  - r-ggraph 
  - r-harmony 
  - r-enrichr 
  - r-devtools
  - bioconductor-ucell 
  - bioconductor-genomicranges 
  - bioconductor-geneoverlap
  - jupyterlab
  - seqtk
  - pip
  - pip:
      - jupyterlab-quarto
