project:
  type: website

website:
  title: "Advanced single cell analysis"
  navbar:
    logo: /img/logo.png
    left:
      - href: index.qmd
        text: Introduction
      - href: Modules/Infected_Plant_Gene_Analysis/Notebook/notebook.source.ipynb
        text: Notebook test
    right: 
      - icon: github
        href: https://github.com/hds-sandbox/AdvancedSingleCell
        aria-label: GitHub
      

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
    include-in-header:
      - file: "resources/bioschema.html"
